version: 2.1
orbs:
  architect: giantswarm/architect@4.24.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit

workflows:
  test-and-push:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: capi-garbage-collector
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-capi-garbage-collector-to-quay
          image: "quay.io/giantswarm/capi-garbage-collector"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
          - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-capi-garbage-collector-to-docker
          image: "docker.io/giantswarm/capi-garbage-collector"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # Ensure that for every commit to master, and for every new release tag,
      # an image gets pushed to the Aliyun registry.
      - architect/push-to-docker:
          name: push-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/capi-garbage-collector"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      # Ensure that for every commit
      # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "capi-garbage-collector"
          requires:
          - push-capi-garbage-collector-to-quay
          - push-capi-garbage-collector-to-docker
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "capi-garbage-collector"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-capi-garbage-collector-to-docker
            - push-capi-garbage-collector-to-quay
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
